### ISSUE TITLE
How to download where to obtain this plugin.

### ISSUE THREAD

**Issue by TitanLV** [PluginsOCSInventory-NG/osinstall#1]
Hi,
where to download/obtain this plugin.

Download button from https://plugins.ocsinventory-ng.org/ shows:

Not Found
The requested URL /undefined was not found on this server.
Thank for replay in advance.

**Comment by gillesdubois** [comment]
Hi,

We are really sorry no release has been made on the repository. That why you found the "Not Found"
We will create it as soon as possible.

Gilles Dubois.

**Comment by steph78630** [comment]
Hi,

you can try here : 

https://github.com/PluginsOCSInventory-NG/osinstall

Regards, Stéphane
